FROM python:3.10-slim

WORKDIR /app

COPY containers/inference/requirements_inference.txt ./requirements_inference.txt
RUN pip install --no-cache-dir -r requirements_inference.txt

COPY common ./common
COPY stages ./stages
COPY inference ./inference

ENTRYPOINT ["python", "inference/serve.py"]
